name: bpi-m2
vendor: BPI <BPI-Sinovoip>
icon: meta/bpi.png
version: 0.01
type: oem

branding:
    name: BPI-M2
store:
    oem-key: 123456

config:
    ubuntu-core:
        autopilot: false

oem:
  hardware:
    platform: sun6i-a31s-bananapi-m2
    architecture: armhf
    partition-layout: system-AB
    bootloader: u-boot
    boot-assets:
      files:
        - path: boot-assets/boot.scr
        - path: boot-assets/boot.cmd
        - path: boot-assets/uEnv.txt
